# Generated by Django 4.2.6 on 2023-12-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
    ]
