# Generated by Django 4.2.6 on 2023-12-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_enable_user_genders_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='genders',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], default='1', max_length=1, verbose_name='性别'),
        ),
    ]
