# Generated by Django 4.2.6 on 2023-12-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_role_enable'),
        ('users', '0004_remove_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='roles.role'),
        ),
    ]
