# Generated by Django 4.2.6 on 2023-12-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='layout',
            field=models.CharField(default='', max_length=50, verbose_name='布局'),
        ),
    ]
