# Generated by Django 4.2.6 on 2023-12-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='layout',
            field=models.CharField(max_length=50, null=True, verbose_name='布局'),
        ),
    ]
