# Generated by Django 4.2.6 on 2023-12-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menu_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='keepAlive',
            field=models.BooleanField(default=False, verbose_name='KeepAlive'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='layout',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='布局'),
        ),
    ]
