# Generated by Django 4.2.6 on 2023-12-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_menu_keepalive_alter_menu_layout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='parent',
            new_name='parentId',
        ),
    ]
